spring.application.name: asct

dashboard.url: http://127.0.0.1



### jwt Settings ###
jwt.secret: a1g2y47dg3dj59fjhhsd7cnewy73j
jwt.expiration: 604800
jwt.tokenheader: X-Auth-Token

spring:
  http:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB